server:
  port: 8088
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cold_storage_oms?useUnicode=true&characterEncoding=UTF-8&connectionCollation=utf8mb4_general_ci&serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: Asia/Shanghai
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 20MB
  redis:
    host: localhost
    port: 6379
    timeout: 300ms
    lettuce:
      pool:
        max-active: 8
        max-idle: 4
      shutdown-timeout: 100ms
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: auto
jwt:
  secret: cold-storage-oms-secret-key-2026
  expire-hours: 24
app:
  upload-dir: uploads
  redis-enabled: true
